[window]
opacity = 0.95
startup_mode = "Maximized"

[window.dimensions]
columns = 94
lines = 32

[font]
size = 14

[font.normal]
family = "Cousine Nerd Font"

[cursor]
blink_interval = 500
blink_timeout = 0

[cursor.style]
shape = "Block"
blinking = "On"
